### ISSUE TITLE
A mistake in a box inertia macro

### ISSUE THREAD

**Issue by stolpa4** [panagelak/Open_Mobile_Manipulator#2]
Hello, @panagelak! Thank you for your wonderful work! I found a little mistake: in the macro for a box inertia, the izz coefficient should be: "${0.0833333 * mass * (x * x + y * y)}", not "${0.0833333 * mass * (x * x + z * z)}"

**Comment by panagelak** [comment]
Thank you @stolpa4 
I will fix it in the next commit
you are welcomed to fork the project and make a pull request
I am not very experienced with that but we can try it out P
Cheers
